### ISSUE TITLE
game crashes after start.

### ISSUE THREAD

**Issue by eskoONE** [AllureOfTheStars/Allure#102]
im not sure how i can help. is there a log i can share? the game just crashes after starting and showing the menu. sometimes its immediately and sometimes it takes a few seconds.

im on windows 10, latest release. 

edit:

should have mentioned that i can move in the menu with the arrow keys before i crash.

**Comment by Mikolaj** [comment]
Hi! Thank you very much for your report. I assume you took your archive from

https://github.com/AllureOfTheStars/Allure/releases

If so, which file exactly was that?

So, when you start the game, it should not show any menu. If you don't press any keys or mouse and let it just show the game map, does it still crash after some time? If not, what it is you have to do to make it crash?

Could you start if from the console and see what error message is displayed?

Then start it with the following extra arguments and paste the full text that gets displayed: ` --dbgMsgSer --logPriority 4 --dumpInitRngs`. 

And then with ` --dbgMsgSer --logPriority 4 --savePrefix play --dumpInitRngs`

Thank you!

**Comment by eskoONE** [comment]
there is no error message displayed at all :/ https://i.imgur.com/2N1z4Ak.png

it just closes, without any errors. i think its on my end. i had visual studio 2019 installed to compile something i needed, which i think may have messed up something with the visual studio c++ redistributables, after i got rid of it again.

does the game depend on any of these?

**Comment by Mikolaj** [comment]
I don't think it should depend on any of the redistributables.

Now that I think about it, on Windows it probably won't show anything in the console, but instead it writes into files `stdout.txt` and `stderr.txt` in the app data dir. Could you try again and track those?

**Comment by eskoONE** [comment]
start is to start the exe i though, turns out, you dont need those. i ran the game without the start command with the arguments u wanted me to run the game with again. 

stderr is empty
[stdout.txt](https://github.com/AllureOfTheStars/Allure/files/3490497/stdout.txt)

**Comment by Mikolaj** [comment]
Oh, it crashes, but there's no error message? That's really weird.

If you have one more spare moment, could you try a dev version from https://ci.appveyor.com/project/Mikolaj/allure/build/artifacts? Also, if you used the installer previously, perhaps try a zipped binary now, or the other way around, to make sure it's not the packaging's fault. 

So, do I get it right, you start it, it displays game map (perhaps some actors moving there) and then it crashes without any keypresses? And if you are quick enough, you can even do something, before it crashes? May it perhaps be a virus scanner killing it after some time?

Actually, could you also try with `--dbgMsgSer --logPriority 1` to verify if it's video driver vs SDL problem perhaps? Thank you.

**Comment by eskoONE** [comment]
i forgot to mention, the game does not crash as long as i dont interact with it it seems. once i either press something the window or or use a key, it crashes. 

other scenario is when i start the game and bring my browser to focus and bring back the game to focus, it crashes there too.

i did try both, the exe and the zip - both behave the same way. the version from the link also crashes the same way. it must be something related to my system then and not your game.

the game starts, but the same behavior as before. this time nothing in the logs at all.

**Comment by Mikolaj** [comment]
Heh, sure, I won't trick you into disabling your virus scanner. ;D

Thank you very much for the extended testing session. I looks like a graphics driver problem or incompatibility with SDL. The fact that there's nothing in the logs, whereas it should show something like

```
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
```

points in that direction. Please let me know when you solve it on your end, if that's really the case. Cheers!

**Comment by Mikolaj** [comment]
Oh, and make sure to try the game out in the browser or on Linux or OSX and let me know if it's fun and whatever other feedback you come up with. :)

**Comment by eskoONE** [comment]
hey, thanks for your time! one last question before i try to fix the problem which appears to be my graphics drivers - whats sdl?

**Comment by Mikolaj** [comment]
A very old, quite low level, but very portable graphics library: https://en.wikipedia.org/wiki/Simple_DirectMedia_Layer

New releases of operating systems and particularly graphics drivers occasionally break it (or they break OpenGL on which SDL often depends), by changing how things work without letting people know in advance.

**Comment by eskoONE** [comment]
turns out it wasnt my gpu driver causing the crash but rivatuner server statistics, an application that i use to cap my framerates with. so in case someone else faces the same issues, get rid of it.

thanks a lot for troubleshooting the problem with me and i am rly sry for wasting your time on that matter, as it wasnt related to your game at all. now its almost 2 am so i dont get to check out your game, but i hope to do so later.

thanks again!

**Comment by Mikolaj** [comment]
No problem. We did it! :)
