### ISSUE TITLE
Add In-Game manual 

### ISSUE THREAD

**Issue by bulbousBullfrog** [AllureOfTheStars/Allure#110]
Having to tab out of the game to search and read the playing.md file may introduce minor friction in the gameplay. Immersion could be retained if that manual could be quickly opened up in-game.

Also, an optional improvement to this could be to make the manual searchable, making it even easier to find the information you need quickly.

This in-game manual would fit naturally if it was accessible similarly or even directly from the help menu or dashboard. Adding it at the end of the help screens would probably be too much, but being able to access it somehow from the help menu would be nice, perhaps by keypress in the help menu.

 For example:

` Press 'm' to view manual, '/' to search manual `

**Comment by Mikolaj** [comment]
The search part is hard (the custom UI doesn't have a text entry widget yet, just number entry) and can then be used for https://github.com/LambdaHack/LambdaHack/issues/73. The rest is rather easy. Generally, it can't hurt to have the manual accessible from the game and bonus points if in the future we can hyperlink with other info in the game, etc.

**Comment by Mikolaj** [comment]
BTW, the manual is already read in in `Client.UI.Content.Screen`, but most of it is currently thrown away.

**Comment by Mikolaj** [comment]
Implemented. The result looks rather badly, especially in LambdaHack, due to small screen and inability to scroll by line, which forces keeping each paragraph on the same screen (if Allure had the same small screen, an extra condition would need to added, forbidding paragraph split if too much of a page is left blank).
